// flow-typed signature: cf515edf9169c850837339a43df97d9c
// flow-typed version: <<STUB>>/dashdash_v^1.14.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dashdash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dashdash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dashdash/lib/dashdash' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dashdash/lib/dashdash.js' {
  declare module.exports: $Exports<'dashdash/lib/dashdash'>;
}
